server:
  port: 8090
spring:
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 16
        max-wait: 50ms
        min-idle: 8
        time-between-eviction-runs: 60000ms
        shutdown-timeout: 100ms
